import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./home/navbar";
import Footer from "./home/footer";
import { SearchProvider } from "./context/searchcontext";



const montserrat = Montserrat({
  subsets: ['latin'], // Choose the subset(s) you need
  weight: ['400', '700'], // Specify the weights you need
});

export const metadata = {
  title: "Singaporemaxi",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <head>
      <link rel="icon" href="\images\Favicon.svg" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={`${montserrat.variable} antialiased`}>
        
        <SearchProvider>
        <Navbar />
        {children}
        <Footer />
        </SearchProvider>
      </body>
    </html>
  );
}
